apiVersion: v1
kind: Service
metadata:
  name: license-server-stub
spec:
  selector:
    app: license-server-stub
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
